# Pipeline for Building and Publishing VSCode theme
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo npm i -g vsce
  displayName: 'Install vsce'

- script: vsce package
  displayName: 'Package to .vsix'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'