# Pipeline for Building and Publishing VSCode theme
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo Installing vsce
    npm install -g vsce
    echo Packaing to .vsix
    vsce package

    echo All DONE!
  displayName: 'Build and Publish'
