# Pipeline for Building and Publishing VSCode theme
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo npm i -g vsce
  displayName: 'Install vsce'

- script: vsce package
  displayName: 'Package to .vsix'

- script: vsce publish -p $env:VSCE_SECRET
  displayName: 'Publish to market place'
  env:
    VSCE_SECRET: $(vsce_publish)
